- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "${JOB_NAME}-config"
    namespace: "${NAMESPACE}"
    labels:
      template: "${JOB_NAME}-config-template"
      cronjob: "${JOB_NAME}"
  data:
    DATABASE_SERVICE_NAME: "${DATABASE_SERVICE_NAME}"
    DEFAULT_PORT: "${DATABASE_DEFAULT_PORT}"
    POSTGRESQL_DATABASE: "${DATABASE_NAME}"
#    BACKUP_STRATEGY: "daily"
#    RETENTION.NUM_BACKUPS: "${NUM_BACKUPS}"
    BACKUP_STRATEGY: "rolling"
    RETENTION.DAILY_BACKUPS: "${DAILY_BACKUPS}"
    RETENTION.WEEKLY_BACKUPS: "${WEEKLY_BACKUPS}"
    RETENTION.MONTHLY_BACKUPS: "${MONTHLY_BACKUPS}"
