---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "{$JOB_NAME}-cronjob-template"
  annotations:
    description: "Scheduled Task to perform a Database Backup"
    tags: "cronjob,backup"
parameters:
  - name: "JOB_NAME"
    displayName: "Job Name"
    description: "Name of the Scheduled Job to Create."
    value: "backup"
    required: true
  - name: "JOB_PERSISTENT_STORAGE_NAME"
    displayName: "Backup Persistent Storage Name"
    description: "Pre-Created PVC to use for backup target"
    value: "NFS-PVC-NAME-GOES-HERE"
    required: true
  - name: "SCHEDULE"
    displayName: "Cron Schedule"
    description: "Cron Schedule to Execute the Job (in UTC)"
# Currently targeting 5:00 AM Daily
    value: "0 13 * * *"
    required: true
  - name: "SOURCE_IMAGE_NAME"
    displayName: "Source Image Name"
    description: "The name of the image to use for this resource."
    required: true
    value: "backup"
  - name: "IMAGE_NAMESPACE"
    displayName: "Image Namespace"
    description: "The namespace of the OpenShift project containing the imagestream for the application."
    required: true
    value: "backup-container"
  - name: "TAG_NAME"
    displayName: "Environment TAG name"
    description: "The TAG name for this environment, e.g., dev, test, prod"
    required: true
    value: "dev"
  - name: "DATABASE_SERVICE_NAME"
    displayName: "Database Service Name"
    description: "The name of the database service."
    required: true
    value: "postgresql"
  - name: "DATABASE_NAME"
    displayName: "Database Name"
    description: "The name of the database."
    required: true
    value: "MyDatabase"
  - name: "DATABASE_DEPLOYMENT_NAME"
    displayName: "Database Deployment Name"
    description: "The name associated to the database deployment resources.  In particular, this is used to wire up the credentials associated to the database."
    required: true
    value: "postgresql"
  - name: "BACKUP_STRATEGY"
    displayName: "Backup Strategy"
    description: "The strategy to use for backups; for example daily, or rolling."
    required: true
    value: "rolling"
  - name: "FTP_SECRET_KEY"
    displayName: "FTP Secret Key"
    description: "The FTP secret key is used to wire up the credentials associated to the FTP."
    required: true
    value: "ftp-secret"
  - name: "FTP_URL"
    displayName: "FTP Server URL"
    description: "The URL of the backup FTP server"
    required: false
    value: ""
  - name: "FTP_USER"
    displayName: "FTP user name"
    description: "FTP user name"
    required: false
    value: ""
  - name: "FTP_PASSWORD"
    displayName: "FTP password"
    description: "FTP password"
    required: false
    value: ""
  - name: "BACKUP_DIR"
    displayName: "The root backup directory"
    description: "The name of the root backup directory"
    required: true
    value: "/backups/"
  - name: "NUM_BACKUPS"
    displayName: "The number of backup files to be retained"
    description: "The number of backup files to be retained.  Used for the `daily` backup strategy.  Ignored when using the `rolling` backup strategy."
    required: false
    value: ""
  - name: "DAILY_BACKUPS"
    displayName: "Number of Daily Backups to Retain"
    description: "The number of daily backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: ""
  - name: "WEEKLY_BACKUPS"
    displayName: "Number of Weekly Backups to Retain"
    description: "The number of weekly backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: ""
  - name: "MONTHLY_BACKUPS"
    displayName: "Number of Monthly Backups to Retain"
    description: "The number of monthly backup files to be retained.  Used for the `rolling` backup strategy."
    required: false
    value: ""
  - name: "BACKUP_PERIOD"
    displayName: "Period (d,m,s) between backups in a format used by the sleep command"
    description: "Period (d,m,s) between backups in a format used by the sleep command"
    required: true
    value: "1d"
  - name: "CONFIG_FILE_NAME"
    displayName: "Config File Name"
    description: "The name of the configuration file."
    required: true
    value: "backup.conf"
  - name: "CONFIG_MAP_NAME"
    displayName: "Config Map Name"
    description: "The name of the configuration map."
    required: true
    value: "backup-conf"
  - name: "CONFIG_MOUNT_PATH"
    displayName: "Config Mount Path"
    description: "The path to use to mount the config file."
    required: true
    value: "/"
  - name: "JOB_SERVICE_ACCOUNT"
    displayName: "Service Account Name"
    description: "Name of the Service Account To Exeucte the Job As."
    value: "default"
    required: true
  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    displayName: "Successful Job History Limit"
    description: "The number of successful jobs that will be retained"
    value: "5"
    required: true
  - name: "FAILED_JOBS_HISTORY_LIMIT"
    displayName: "Failed Job History Limit"
    description: "The number of failed jobs that will be retained"
    value: "2"
    required: true
  - name: "JOB_BACKOFF_LIMIT"
    displayName: "Job Backoff Limit"
    description: "The number of attempts to try for a successful job outcome"
    value: "0"
    required: false
objects:
